#!/bin/bash

# Get the name of the branch being pushed
while read local_ref local_sha remote_ref remote_sha
do
    BRANCH=$(echo $remote_ref | sed -e 's,refs/heads/,,')

    # Only execute the pre-push logic for the master branch
    if [ "$BRANCH" == "master" ]; then
        echo "Executing pre-push hook for master branch"
        # Add your pre-push logic here
        #File name should be pre-push
        SCRIPT_DIR="$(dirname "$0")"
        # Path to your file
        PRE_PUSH_SCRIPT_DIR_LINUX="$SCRIPT_DIR/../../0.MASTER/1.PRE_PUSH/1.LINUX"
        PRE_PUSH_SCRIPT_DIR_WIN="$SCRIPT_DIR/../../0.MASTER/1.PRE_PUSH/2.WIN"

        # Check the operating system and execute the appropriate command
        if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
            for PRE_PUSH_SCRIPT_LINUX in "$PRE_PUSH_SCRIPT_DIR_LINUX"/*.sh;
            do
                bash "$PRE_PUSH_SCRIPT_LINUX"
            done
        elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ] || [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
            if command -v powershell &> /dev/null; then
                for PRE_PUSH_SCRIPT_WIN in "$PRE_PUSH_SCRIPT_DIR_WIN"/*.sh;
                do
                    powershell.exe -ExecutionPolicy Bypass -File "$PRE_PUSH_SCRIPT_WIN"
                done
            else
                echo "PowerShell is not available on this system."
            fi
        else
            echo "Unsupported operating system."
        fi
        echo "pre-push script executed successfully."
    else
        echo "Pre-push hook is not executed for branch: $BRANCH"
        exit 0
    fi
done
